[build]
builder = "NIXPACKS" 
buildCommand = "cd apps/api && npm ci && npm run build"

[deploy]
startCommand = "cd apps/api && npx prisma generate && npx prisma migrate deploy && npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10