[build]
builder = "NIXPACKS"
buildCommand = "cd apps/api && npm ci && npm run build && npx prisma generate && npx prisma db push"

[deploy]
startCommand = "cd apps/api && npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10